### ISSUE TITLE
v0.4.4 warning for use of deprecated item

### ISSUE THREAD

**Issue by zonyitoo** [kornelski/rust-security-framework#100]
```
warning: use of deprecated item 'imp::security_framework::import_export::Pkcs12ImportOptions::keychain': Replaced by `os::macos::import_export::Pkcs12ImportOptionsExt::keychain`
   --> src/imp/security_framework.rs:137:14
    |
137 |             .keychain(keychain)
    |              ^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated item 'imp::security_framework::import_export::Pkcs12ImportOptions::keychain': Replaced by `os::macos::import_export::Pkcs12ImportOptionsExt::keychain`
   --> src/imp/security_framework.rs:137:14
    |
137 |             .keychain(keychain)
    |              ^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default
```

This is the cause of CI failure in: https://github.com/sfackler/rust-native-tls/pull/157 .

**Comment by kornelski** [comment]
That's intentional. It's going away in 1.0. I suggest adding `#[allow(deprecated)]` if you're using 0.4.

**Comment by zonyitoo** [comment]
CI sets `-D warnings`

https://github.com/sfackler/rust-native-tls/blob/e3ebe77fe86109a05c8e835a640de886135a9daa/.circleci/config.yml#L40

How about adding a `Pkcs12ImportOptionsExt`? @LuoZijun

**Comment by kornelski** [comment]
Do you mean it's affected by the warning inside security-framework? I assumed "cap lints" feature prevents such problems.

Can you change RUSTFLAGS to normal `#[deny(warning)]` in your crate/PR? That should limit it to your crate only.
