### ISSUE TITLE
Please git tag releases

### ISSUE THREAD

**Issue by stepancheg** [kornelski/rust-security-framework#113]
The last release is 2.0.0, but there's no git tag for it.

Tag is helpful to do debugging: to checkout exact version locally and modify it.

**Comment by steven-joruk** [comment]
@kornelski I'm sure you've seen it but [cargo-release](https://github.com/sunng87/cargo-release) is useful to handle the tagging and some sanity checks for publishing.

**Comment by kornelski** [comment]
Tagged
