### ISSUE TITLE
Consider removing feature "alpn"

### ISSUE THREAD

**Issue by stepancheg** [kornelski/rust-security-framework#119]
Is there a reason to not enable this feature unconditionally?

Currently even when feature is on, it is not a guarantee that ALPN will actually work. And when feature is off, it just hides some functions, and nothing more.

**Comment by kornelski** [comment]
I think it was added behind a flag, because it requires 10.13, and uses dlsym as a fallback. I'm not sure what are compatibility consequences of this.

**Comment by stepancheg** [comment]
OK, no worries.
