### ISSUE TITLE
security-framework can't target osx <10.4 due SecTrustEvaluateWithError

### ISSUE THREAD

**Issue by marsam** [kornelski/rust-security-framework#124]
Hi:
Since the inclusion of [`SecTrustEvaluateWithError`](https://developer.apple.com/documentation/security/2980705-sectrustevaluatewitherror) in 2.1.0, security-framework can't be built on macosx <10.4. 
Some of those versions still have an usage share https://www.statista.com/statistics/944559/worldwide-macos-version-market-share/

My personal scenario is that I'm using [`nix`](https://nixos.org/) and they use MACOSX_DEPLOYMENT_TARGET=10.12, and this would prevent the use of some packages on macosx.

Unfortunately, I'm not familiar enough with Rust to create a PR.

**Comment by kornelski** [comment]
Oops, fixed.
