### ISSUE TITLE
Version 2.1.3 and 2.2.0 missing from Crates.io

### ISSUE THREAD

**Issue by ddeville** [kornelski/rust-security-framework#128]
Hello!

It looks like version 2.1.3 and version 2.2.0 were committed to the repo but never tagged or pushed to Crates.io. Is this just an omission or mostly WIP?

Thanks

**Comment by kornelski** [comment]
A bit of both. Thanks for the reminder. I've published them.

**Comment by ddeville** [comment]
Thanks!
