### ISSUE TITLE
SecCertificateCopyPublicKey broken with aarch64-apple-darwin

### ISSUE THREAD

**Issue by brandonweeks** [kornelski/rust-security-framework#143]
This isn't technically an issue with this crate, however I thought I file it lest anyone runs into it or knows how to troubleshoot further.

```rust
// OK
// $ cargo run --target x86_64-apple-darwin
//
// FAIL
// $ cargo run --target aarch64-apple-darwin
use core_foundation::base::*;
use core_foundation::data::*;
use std::ptr;

pub enum OpaqueSecCertificateRef {}
pub type SecCertificateRef = *mut OpaqueSecCertificateRef;

pub enum OpaqueSecKeyRef {}
pub type SecKeyRef = *mut OpaqueSecKeyRef;

#[link(name = "Security", kind = "framework")]
extern "C" {
    pub fn SecCertificateCreateWithData(
        allocator: CFAllocatorRef,
        data: CFDataRef,
    ) -> SecCertificateRef;
    pub fn SecCertificateCopyPublicKey(
        certificate: SecCertificateRef,
        key: *mut SecKeyRef,
    ) -> OSStatus;
}

fn main() {
    let der_data = CFData::from_buffer(include_bytes!("../server.der"));
    let certificate = unsafe {
        SecCertificateCreateWithData(kCFAllocatorDefault, der_data.as_concrete_TypeRef())
    };
    let mut public_key = ptr::null_mut();
    let status;
    status = unsafe { SecCertificateCopyPublicKey(certificate, &mut public_key) };
    assert_eq!(0, status);
}
```
Crate: https://github.com/brandonweeks/repro

Steps to reproduce:
- `git clone https://github.com/brandonweeks/repro`
- `cargo test --aarch64-apple-darwin` on a Apple M1 device

Expected results: `SecCertificateCopyPublicKey` returns 0.

Actual results: `SecCertificateCopyPublicKey` returns random garbage that never corresponds to a valid `OSStatus` value.

This does not reproduce when with `cargo test --target x86_64-apple-darwin`. I was not able to reproduce using Swift to call the same methods.

- [aarch64-apple-darwin asm](https://gist.github.com/brandonweeks/1d9b2b6455c2ef1f17ca66ecd237dc1c)
- [x86_64-apple-darwin asm](https://gist.github.com/brandonweeks/bde2f10e5740cd3a5314095ee8bb0351)

**Comment by brandonweeks** [comment]
https://developer.apple.com/documentation/security/1396096-seccertificatecopypublickey?language=objc

Oh, hah, this is because macOS on aarch64 uses the iOS form of the function...

**Comment by brandonweeks** [comment]
C:
```asm
bl	_SecCertificateCopyPublicKey
str	w0, [sp, #44]
```

Rust:
```asm
bl	_SecCertificateCopyPublicKey$LEGACYMAC
str	w0, [sp, #36]
```

Totally overlooked the `$LEGACYMAC` suffix on the function that is missing from the rust version. That must be it.

**Comment by kornelski** [comment]
Maybe M1 is returning a pointer, like the iOS version?
