### ISSUE TITLE
Linker Error on iOS

### ISSUE THREAD

**Issue by utahmike** [kornelski/rust-security-framework#150]
We're getting the following linker error when linking against your crate via transitive dependency in the reqwest crate:

```
Undefined symbols for architecture x86_64:
  "_SecTrustCopyAnchorCertificates", referenced from:
      security_framework::trust::SecTrust::copy_anchor_certificates::h9424d53ab4c6030f in libkmc.a(security_framework-4fa0798ff7118d5b.security_framework.7dbtx6tq-cgu.9.rcgu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

[SecTrustCopyAnchorCertificates](https://developer.apple.com/documentation/security/1401507-sectrustcopyanchorcertificates) is not available on iOS. It looks like this symbol was introduced recently in https://github.com/kornelski/rust-security-framework/commit/506e3e941bd802d7ad3f75176aa3f7010cb6f32c and should probably be conditionally compiled.

**Comment by kornelski** [comment]
Thanks. This should be fixed in 2.4.1
