### ISSUE TITLE
impl common traits for public facing types

### ISSUE THREAD

**Issue by garritfra** [kornelski/rust-security-framework#151]
I'm working on implementing [common traits](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits) for public facing types via [this](https://github.com/sfackler/rust-native-tls/issues/207) issue on `rust-native-tls`.

Unfortunately this doesn't seem trivial, since some types are declared using the `declare_TCFType` macro, so deriving them is not possible. I tried implementing them by hand, but this doesn't seem to have an effect.

<details>
<summary>Implementation of traits for `SecIdentity`</summary>

```rs
declare_TCFType! {
    /// A type representing an identity.
    ///
    /// Identities are a certificate paired with the corresponding private key.
    SecIdentity, SecIdentityRef
}
impl_TCFType!(SecIdentity, SecIdentityRef, SecIdentityGetTypeID);

impl Copy for SecIdentity {}
impl Clone for SecIdentity {}
impl Eq for SecIdentity {}
impl PartialEq for SecIdentity {}
impl Ord for SecIdentity {}
impl PartialOrd for SecIdentity {}
impl Hash for SecIdentity {}
impl Debug for SecIdentity {}
impl Default for SecIdentity {}
```
</details>

<details>
<summary>Error describing that `SecIdentity` doesn't implement `Copy`</summary>

```
error[E0204]: the trait `Copy` may not be implemented for this type
  --> src/imp/security_framework.rs:78:10
   |
78 | #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
   |          ^^^^
79 | pub struct Identity {
80 |     identity: SecIdentity,
   |     --------------------- this field does not implement `Copy`
81 |     chain: Vec<SecCertificate>,
   |     -------------------------- this field does not implement `Copy`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
</details>

I must say that I'm not familiar with this macro, so it could just be that I'm missing something. Do you know a way around this issue?

Thanks for feedback of any kind!

**Comment by kornelski** [comment]
Types that own heap-allocated data like `Vec` are fundamentally incompatible with the `Copy` trait. That's by design — `Copy` means there's nothing that needs to be done when copying or discarding the values, and that's not true for this type.

If you're implementing `Copy`, because an error message told you so, it's a logic error in your program. You probably need to wrap it in `Arc`, or ensure you use it from one place at a time only.

**Comment by garritfra** [comment]
Thanks for the hint, I actually wasn't aware of this.

I dug into the `impl_TCFType` and found that it already implements `PartialEq` and `Eq`. The only part I was originally interested in was `Hash` and given your explanation about `Copy`, I reduced the scope of the linked PR to just `Hash`.
