### ISSUE TITLE
Web form password

### ISSUE THREAD

**Issue by Tarang** [kornelski/rust-security-framework#176]
Is it possible to use a web form password, in addition to the internet and generic password types?

I'm not too sure of what the internals of the OS X security framework look like, is a web form password a variant of the internet password?

**Comment by kornelski** [comment]
I don't think so. Apple has removed and locked down these APIs to the point that even Chrome has given up completely and deleted their Keychain integration:

https://bugs.chromium.org/p/chromium/issues/detail?id=466638
