### ISSUE TITLE
Infinite run on read_to_end with pkcs12

### ISSUE THREAD

**Issue by ragoso** [kornelski/rust-security-framework#182]
I'm coming from a reqwest implementation where I'm getting a "`peer cert is valid, or was ignored if verification disabled`" error

To validate if the error comes from the security-framework, I created the following test, but for some reason it runs infinitely.

```
#[test]
    fn load_page_with_pkcs12()
    {
        let pkcs12_der = include_bytes!("../test/my_cert.pfx");
        let ctxx = ServerBuilder::from_pkcs12(pkcs12_der, "1234").unwrap();

        let mut ctx = p!(SslContext::new(
            SslProtocolSide::CLIENT,
            SslConnectionType::STREAM
        ));

        ctx.set_certificate(&ctxx.identity, &ctxx.certs).unwrap();

        p!(ctx.set_peer_domain_name("hom1.nfe.fazenda.gov.br"));
        let stream = p!(TcpStream::connect("hom1.nfe.fazenda.gov.br:443"));
        let mut stream = p!(ctx.handshake(stream));
        p!(stream.write_all(b"GET /NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx HTTP/1.0\r\nHost: hom1.nfe.fazenda.gov.br\r\n\r\n"));
        p!(stream.flush());
        let mut buf = vec![];
        p!(stream.read_to_end(&mut buf));
        println!("{}", String::from_utf8_lossy(&buf));

    }
```

```
 Compiling security-framework v2.9.0 (/Users/matheusragoso/Projects/rust-security-framework/security-framework)
    Finished test [unoptimized + debuginfo] target(s) in 1.65s
     Running unittests src/lib.rs (target/debug/deps/security_framework-df6cd6b7a6b0fc69)

running 1 test
test secure_transport::test::load_page_with_pkcs12 has been running for over 60 seconds
```

What could be happening?

**Comment by kornelski** [comment]
If I run `curl -v hom1.nfe.fazenda.gov.br:443` I get no reply either, so I think it's just the server not responding.

**Comment by ragoso** [comment]
> If I run `curl -v hom1.nfe.fazenda.gov.br:443` I get no reply either, so I think it's just the server not responding.

Maybe it has something to do with the region.
```
➜  ~ curl -v hom1.nfe.fazenda.gov.br:443
*   Trying 189.9.67.82:443...
* Connected to hom1.nfe.fazenda.gov.br (189.9.67.82) port 443 (#0)
> GET / HTTP/1.1
> Host: hom1.nfe.fazenda.gov.br:443
> User-Agent: curl/7.87.0
> Accept: */*
```

try in production please: `curl -v www1.nfe.fazenda.gov.br:443`

**Comment by kornelski** [comment]
Unfortunately, I can't help you with this. I only "keep the lights on" in this crate. If you need some interfaces added or have found a bug I can merge your PR.

**Comment by ragoso** [comment]
> Unfortunately, I can't help you with this. I only "keep the lights on" in this crate. If you need some interfaces added or have found a bug I can merge your PR.

Of course, I forgot about good open source practices, sorry.

I sent you a PR #183

**Comment by kornelski** [comment]
Thanks. I've released this.
