### ISSUE TITLE
Method not found but actually exists

### ISSUE THREAD

**Issue by emanuele-em** [kornelski/rust-security-framework#184]
<img width="811" alt="image" src="https://github.com/kornelski/rust-security-framework/assets/100081325/c2766f88-3ef9-4c8e-a57e-8f585dda8892">

this appears but the method actually exists, also on repo [[here](https://github.com/kornelski/rust-security-framework/blob/main/security-framework/src/trust_settings.rs#LL131C1-L141C1)]

It does not even appear in the documentation

**Comment by kornelski** [comment]
It exists only on macOS. You may be building for iOS or another platform.
