### ISSUE TITLE
rust-version vs MSRV in CI

### ISSUE THREAD

**Issue by waywardmonkeys** [kornelski/rust-security-framework#208]
In https://github.com/kornelski/rust-security-framework/commit/7bb4b4a855350ac25a7562cdc5ae6ee9fdf35b66, there was a change made to CI so that it is checking against 1.65 now rather than 1.60.

However, the `Cargo.toml` for `security-framework` still lists 1.60 as the MSRV.

Is it intended to raise the MSRV to 1.65?

I did a quick build locally with 1.60 and it worked, once I changed the version on `cc` to 1.0.94.

I was looking at this as I'm about to bump the MSRV on `core-foundation` to a minimum of 1.60 and was looking at where the downstream dependencies are at.

**Comment by kornelski** [comment]
IIRC I've bumped CI due to difficulty of testing with 1.60, but didn't bump the crate metadata in case it still worked. I don't mind requiring 1.65 or newer. 

The difference may be irrelevant now, since probably less than 0.05% of users are below 1.65: https://lib.rs/stats#rustc-usage
