### ISSUE TITLE
SecKey::ec uses deprecated `kSecAttrKeyTypeEC`

### ISSUE THREAD

**Issue by teidesu** [kornelski/rust-security-framework#209]
...and there is no way to use the new `kSecAttrKeyTypeECSECPrimeRandom` without patching that in or manually building CFDictionary

ref: https://developer.apple.com/documentation/security/ksecattrkeytypeec

**Comment by kornelski** [comment]
Please make a PR with an update

**Comment by crashdump** [comment]
This PR would address that: [https://github.com/kornelski/rust-security-framework/pull/218](https://github.com/kornelski/rust-security-framework/pull/218)
