### ISSUE TITLE
security-framework-sys: Update core-foundation-sys dependency

### ISSUE THREAD

**Issue by kpcyrd** [kornelski/rust-security-framework#71]
security-framework-sys currently depends on:

```
core-foundation-sys = "0.5.1"
```

even though the latest released version is 0.6.2. Would you mind bumping the dependency? Thanks!

**Comment by kornelski** [comment]
This is done on master

**Comment by SergejJurecko** [comment]
Do you have any plans for when next release will be made?

**Comment by kornelski** [comment]
Published v0.2.4-beta

**Comment by SergejJurecko** [comment]
0.2.4-beta works fine for me

**Comment by sfackler** [comment]
core-foundation-sys is a public dependency of security-framework-sys, so this is a breaking change.

**Comment by kornelski** [comment]
Yes, sorry. I was too optimistic about it not breaking stuff.

**Comment by kornelski** [comment]
I'll bump it to 0.3 after all.

**Comment by kornelski** [comment]
I've yanked 0.2.4 and re-released it as 0.3.0
