### ISSUE TITLE
subjectPublicKeyInfo and pinning

### ISSUE THREAD

**Issue by SergejJurecko** [kornelski/rust-security-framework#74]
I have basic pinning implementation imported from TrustKit in mio_httpc. What is required is exposing subjectPublicKeyInfo from a certificate.

https://github.com/SergejJurecko/mio_httpc/blob/master/src/tls_api/apple.rs
Imported from:
https://github.com/datatheorem/TrustKit/blob/master/TrustKit/Pinning/TSKSPKIHashCache.m

I have been working on making this available in rust-native-tls. I'm not sure where it would be correct to have this implementation, native-tls or here. It goes further then simply wrapping over SecurityFramework API, but it is something that might be useful for someone else other than native-tls.

Would you accept a PR that would expose the pubkey (probably better named) function in SecCertificate like I have in mio_httpc?

**Comment by kornelski** [comment]
Yes.

All the `extern "C"` bits belong to security-framework-sys.

As for the higher-level API, maybe you could first expose closer equivalents to Cocoa's functions? e.g. a wrapper just around SecKeyCopyAttributes, not specific to the pubkey?
