### ISSUE TITLE
TrustSettings does not support iOS

### ISSUE THREAD

**Issue by quininer** [kornelski/rust-security-framework#85]
<img width="796" alt="bad-sf-ios" src="https://user-images.githubusercontent.com/6286761/68274447-22667d00-00a4-11ea-9f3f-1e26461e79ca.png">

![Screenshot_20191106_144942](https://user-images.githubusercontent.com/6286761/68274666-afa9d180-00a4-11ea-9161-6dc74f2ef888.png)

The [`SecTrustSettingsCopyTrustSettings`](https://developer.apple.com/documentation/security/1400261-sectrustsettingscopytrustsetting?language=objc) seems to only support macOS instead of iOS, which cause us to have a link error.

**Comment by kornelski** [comment]
Thanks. I've released 0.3.3 with this set as macos-only

**Comment by quininer** [comment]
Thank you!
