### ISSUE TITLE
Authorization Services

### ISSUE THREAD

**Issue by steven-joruk** [kornelski/rust-security-framework#89]
I'm currently working on adding support for [Authorization Services](https://developer.apple.com/documentation/security/authorization_services?language=objc). Is this something you'd be interested in a PR for?

Just thought I'd add an issue to track it in case someone else was thinking of doing the same.

**Comment by kornelski** [comment]
Yes, please!

**Comment by steven-joruk** [comment]
I'm not too far off completing this now, but your input would be great on a few things before I finish it off and open a PR:

1. Is adding a dependency on `bitflags` okay? There are 6 authorization flags the users need to be able to combine.
1. I've not been able to find an obvious way to give users a `CFDictionary<CFStringRef, CFTypeRef>` from the `AuthorizationRightGet` implementation. I guess I could create one manually and try mapping each CFTypeRef to a specific type, do you know of a better way?
1. Would you prefer the APIs to take rust types and convert them to CF types internally, or have the user pass in CF types? Rust types would be much nicer to use, but would result in copies. It's probably possible to add a builder pattern which accepts either for best of both worlds for `AuthorizationItemSet`, but it might be over complicating things for a rarely used API.

**Comment by kornelski** [comment]
1. I'm not sure about bitflags. It is a common dependency, so probably not a big deal. Is it 6 different sets of flags, or one set of flags with 6 options?

2. It depends, are we talking about -sys crate or higher-level API? In the sys, it doesn't need to be type-safe, so it can be an untyped CFDictionary. In higher-level wrapper don't expose the CFDictionary, but check CF types and convert them to something rust-idiomatic.

3. Split into -sys, which exposes everything as Apple does, and a non-sys wrapper, which uses only Rust types, none of Apple's. Copying is OK for items that aren't large or used in loops. If something is expensive to copy, you can also wrap a CF object in a NewType.

**Comment by steven-joruk** [comment]
Thanks! Yeah where I talk about abstractions it’s not the sys crate. I’ll just open a PR for more feed back.
