### ISSUE TITLE
Recent MSRV is 1.34.0. Document? Test?

### ISSUE THREAD

**Issue by dekellum** [kornelski/rust-security-framework#90]
This may just be an FYI. Close if your prefer.

Looks like as part of #82, released in 0.3.2, this crate started using `std::convert::TryFrom` which I believe is MSRV 1.34.0:

``` txt
   Compiling security-framework v0.3.3

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)

  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/security-framework-0.3.3/src/trust_settings.rs:13:5

   |

13 | use std::convert::TryFrom;

   |     ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'try_from' (see issue #33417)

  --> /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/security-framework-0.3.3/src/trust_settings.rs:64:15

   |

64 |         match u32::try_from(value).ok() {

   |               ^^^^^^^^^^^^^

```

I couldn't find any position for what the expected MSRV is here.  Not sure if there is any CI for this, etc.

**Comment by kornelski** [comment]
That one is a small thing, so I've changed it. 

I usually only support last 2 stable versions, but maybe this crate needs more. I'll think about it.
