### ISSUE TITLE
dlsym.rs is missing a libc dependency

### ISSUE THREAD

**Issue by cyang1** [kornelski/rust-security-framework#96]
Trying to use this crate with either `alpn` or `session-tickets` and _not_ specifying `OSX_10_13` results in:
```
error[E0432]: unresolved import `libc`
 --> security-framework-0.4.2-alpha.1/src/dlsym.rs:8:5
  |
8 | use libc;
  |     ^^^^ no `libc` in the root
```

**Comment by kornelski** [comment]
I've readded libc

**Comment by cyang1** [comment]
Same error, there probably needs to be an `extern crate libc` somewhere (or a switch to Rust 2018).

**Comment by kornelski** [comment]
Can you make a PR with a working code?
